### ISSUE TITLE
Cluster Statistics: H-L and Trade Count

### ISSUE THREAD

**Issue by Sebastian7700** [AtasPlatform/Indicators#5]
Hi there,
I have some suggestions for improvement of the Cluster Statistics indicator.

**High-Low**
In the Cluster Statistics indicator, it would be great to have a High-Low functionality, e.g:
Candle Open: 10.050$
Candle Low: 10.000$
Candle High: 10.460$
Candle Close: 10.200$
10.460 - 10.000 = 460
=> Candle H-L: 460
And this is then displayed in the Cluster Statistics for every candle.
(open and close of the candle are irrelevant)

The thinking behind this is as follows:
Large candles with small volume are considered weak price action. The large candle could be due to slippage.
Small candles with large volume are considered strong price action. After breaking, one would expect the level to be defended.
Yes, one could just look at the candle but I think it would be helpful to have it in the statistics.

**Trade Count**
In a similar notion, it would also be great to have the Trade Count displayed in the Cluster Statistics.
By this, I mean the number of trades executed in a candle (regardless of volume).

**Comment by CCefman** [comment]
Hi Sebastian, 

Not sure if you’ve checked yet but this has been implemented 2 days ago. No trade count as of yet but I also agree that this would be very beneficial. Fingers crossed

**Comment by Sebastian7700** [comment]
Hi @CCefman,

can you tell me how it's called, maybe I'm dumb but I can't find it.

Thanks, mate.

**Comment by CCefman** [comment]
Sorry mate, I should’ve worded it better. You won’t be able to see it in ATAS just yet but if you check the “Develop” branch you’ll see that Stig has added the necessary code to the indicator. I guess now it’s just a matter of time before we get the new update.

**Comment by CCefman** [comment]
Stig has added the trade count as well!! Thanks for opening this issue and thanks Stig for something this out.

**Comment by Sebastian7700** [comment]
Oh cool, that's awesome, thanks for telling me, and thanks @Stig4all for implementing!
